### ISSUE TITLE
major fixes

### ISSUE THREAD

**Issue by kauste** [front-end-by-rimantas/35-grupe-portfolio-docland#126]
- buttons angle icon
- footer
- header nav

**Comment by Laurisdid** [comment]
buttons angle icon done 
header nav done

footer   ;(

**Comment by Laurisdid** [comment]
Course Benefit carousel added

**Comment by Laurisdid** [comment]
footer  has new  margin "
.row1 {
    margin-left:10% ;
    margin-right:10%;
  }"
